CREATE TABLE CUSTOMERS (
    id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(30)
);

CREATE TABLE CDS (
    id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    title VARCHAR(30),
    yeardb INTEGER
);

CREATE TABLE BORROWS (
    id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    cdid INTEGER,
    customerid INTEGER,
    active INTEGER
);