CREATE TABLE CUSTOMERS (
    id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(30)
);

CREATE TABLE CDS (
    id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    title VARCHAR(30),
    yeardb INTEGER
);